# Generated by Django 4.1.7 on 2023-04-08 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SystemPermissions',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dbb_accounts.permission')),
            ],
            options={
                'verbose_name': 'System Permission',
                'verbose_name_plural': 'System Permissions',
                'permissions': (('dbb_edit_permissions', 'Can change permissions of Operators.'), ('dbb_edit_operators', 'Can edit profiles from others Operators.'), ('dbb_view_operators', 'Can view all Operators Profile.'), ('dbb_add_operators', 'Can view add new Operators.')),
            },
            bases=('dbb_accounts.permission',),
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'operators',
            },
        ),
    ]
